# Generated by Django 4.2.1 on 2023-06-04 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('systemid', models.UUIDField()),
                ('owner', models.UUIDField()),
                ('storageid', models.CharField(max_length=200)),
                ('instore', models.BooleanField()),
                ('size', models.IntegerField()),
                ('accesslevel', models.IntegerField()),
                ('type', models.IntegerField()),
                ('media', models.IntegerField()),
                ('added', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xscore', models.IntegerField()),
                ('simhash', models.CharField(max_length=200)),
                ('bucket', models.CharField(max_length=200)),
                ('keyvalues', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('accesslevelh', models.CharField(max_length=200)),
                ('mediah', models.CharField(max_length=200)),
                ('simhashh', models.CharField(max_length=200)),
                ('typeh', models.CharField(max_length=200)),
                ('randomid', models.UUIDField()),
                ('bucketh', models.CharField(max_length=200)),
                ('indexfile', models.CharField(max_length=200)),
                ('historyfile', models.CharField(blank=True, max_length=200, null=True)),
                ('perfectmatch', models.BooleanField()),
                ('group', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TLD',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tagsh',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('class_field', models.IntegerField()),
                ('classh', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('valueh', models.CharField(max_length=200)),
                ('main_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagshs', to='app.maindata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target', models.UUIDField()),
                ('relation', models.IntegerField()),
                ('main_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='app.maindata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='app.tld')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentLine',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line', models.BinaryField()),
                ('email', models.BinaryField()),
                ('email_hash', models.CharField(max_length=64)),
                ('password', models.BinaryField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_lines', to='app.domain')),
                ('main_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_lines', to='app.maindata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
