# Generated by Django 4.2.1 on 2023-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeakedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('source_of_leak', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_leak', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Leaked Credentials',
            },
        ),
    ]
